---
baseURL: "https://foundation.red-lang.org/"
title: The Red Foundation
languageCode: "en-us"
metaDataFormat: yaml
theme: "featherweight"
pluralizeListTitles: false
enableRobotsTXT: true
defaultContentLanguage: "en"
enableMissingTranslationPlaceholders: true
paginate: 5 # Number of posts per page

permalinks:
  blog: /:section/:year/:month/:slug/
  events: /:section/:year/:month/:slug/

taxonomies:
  category: category
  tag: tags

outputs:
  home:
    - HTML
    - JSON
  section:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - JSON

languages:
  en:
    LanguageName: "English"
    params:
      Title: "Red Foundation"
      CopyrightHTML: "Copyright &#xA9; 2018 The Red Foundation"
    menu:
      main:
        - Name: "About"
          Weight: 1
          Identifier: "about"
          URL: "/about/"
        - Name: "Blog"
          Weight: 2
          Identifier: "blog"
          URL: "/blog/"
        - Name: "Events"
          Weight: 3
          Identifier: "events"
          URL: "/events/"
        - Name: "Contact"
          Weight: 4
          Identifier: "contact"
          URL: "/contact/"
        - Name: "Join Red"
          Weight: 5
          Identifier: "join"
          URL: "/join/"
  fr:
    LanguageName: "Français"
    params:
      Title: "Red Foundation"
      CopyrightHTML: "Droits d'auteur &#xA9; 2018 The Red Foundation"
    blackfriday:
      angledQuotes: true
    menu:
      main:
        - Name: "About"
          Weight: 1
          Identifier: "about"
          URL: "/about/"
        - Name: "Blog"
          Weight: 2
          Identifier: "blog"
          URL: "/blog/"
        - Name: "Events"
          Weight: 3
          Identifier: "events"
          URL: "/events/"
        - Name: "Contact"
          Weight: 4
          Identifier: "contact"
          URL: "/contact/"
        - Name: "Join Red"
          Weight: 5
          Identifier: "join"
          URL: "/join/"
  cn:
    LanguageName: "简体中文"
    params:
      Title: "Red Foundation"
      CopyrightHTML: "Copyright &#xA9; 2018 The Red Foundation Ltd"
    menu:
      main:
        - Name: "About"
          Weight: 1
          Identifier: "about"
          URL: "/about/"
        - Name: "Blog"
          Weight: 2
          Identifier: "blog"
          URL: "/blog/"
        - Name: "Events"
          Weight: 3
          Identifier: "events"
          URL: "/events/"
        - Name: "Contact"
          Weight: 4
          Identifier: "contact"
          URL: "/contact/"
        - Name: "Join Red"
          Weight: 5
          Identifier: "join"
          URL: "/join/"

params:
  sponsors:
    - Name: "Microsoft"
      Weight: 1
      URL: "https://www.microsoft.com/"
      logo_src: "/images/microsoft-logo.png"
    - Name: "Microsoft"
      Weight: 2
      URL: "https://www.microsoft.com/"
      logo_src: "/images/microsoft-logo.png"
    - Name: "Microsoft"
      Weight: 3
      URL: "https://www.microsoft.com/"
      logo_src: "/images/microsoft-logo.png"
    - Name: "Microsoft"
      Weight: 4
      URL: "https://www.microsoft.com/"
      logo_src: "/images/microsoft-logo.png"
  navigation:
    social:
      - Name: "Reddit"
        Weight: 1
        Identifier: "reddit-alien"
        URL: "https://www.reddit.com/r/redlang/"
      - Name: "Facebook"
        Weight: 2
        Identifier: "facebook-square"
        URL: "https://facebook.com"
      - Name: "Twitter"
        Weight: 3
        Identifier: "twitter"
        URL: "https://twitter.com/red_lang"
      - Name: "Gitter"
        Weight: 4
        Identifier: "gitter"
        URL: "https://gitter.im/red/red"
      - Name: "GitHub"
        Weight: 5
        Identifier: "github"
        URL: "https://github.com/red/red"
      - Name: "Telegram"
        Weight: 6
        Identifier: "telegram"
        URL: "https://t.me/redofficial"
    ecosystem:
      - Name: "Red Language"
        Weight: 1
        Identifier: "redlang"
        URL: "https://red-lang.org"
      - Name: "Red Foundation"
        Weight: 2
        Identifier: "foundation"
        URL: "https://foundation.red-lang.org"
      - Name: "Red ICO"
        Weight: 3
        Identifier: "ico"
        URL: "https://ico.red-lang.org"
      - Name: "Fullstack Technologies"
        Weight: 4
        Identifier: "fullstack"
        URL: "https://fullstack.red-lang.org"
---
